# Prometheus Configuration File
global:
  scrape_interval: 15s  # Scrape target setiap 15 detik
  resolve_timeout: 5m   # Waktu penyelesaian alert

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

route:
  group_by: ['alertname']
  receiver: 'slack'
  routes: []

receivers:
  - name: 'slack'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#alert'
        username: 'Alertmanager'
        title: '{{ .CommonLabels.alertname }}'
        text: |
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
          {{ end }}
